### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/moondance#1]
## Google Fonts Latin Plus coverage

- [x] Design all the glyphs required in the [GF Latin Plus encoding](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/filter%20lists/nice%20names/plus_unique-glyphs.txt)
- [x] Create all the comb marks as mentioned below
- [x] Leave only the compound glyphs (e.g. `adblgrave`) marked in dark grey as pending to be created using the components

----

## Diacritics

- [x] Please ensure the definitive design is adjusted in the combining marks, so they will be ready to create the compound glyphs.
- [x] Once the definitive design is ensured in the `comb` marks Legacy marks, delete the legacy marks and add them back so they are made using the `comb` marks as components.
- [x] Diacritics need to be balanced (in weight, size, contrast) and matching the style of the typeface design.
- [x] Adjust the vertical position using glyphs app locked guidelines.
- [x] Ensure related marks are consistent between them, e.g. `caron` and `circumflex`
- [x] Caron.alt need to have the alternate shape used in `Ľ` [Slovak](https://en.wikipedia.org/wiki/%C4%BD) On page 30 of [this document](http://theinsectsproject.eu/wp-content/uploads/2017/05/Insects-Project-2nd-edition_screen.pdf) you can find detailed info around the vertical Caron.
- [x] Leave a 0 sidebearings value for the marks

----
## Glyphs

- [x] The `ampersand` and `Eng` need to be consistent (in size and style) with the font. See [RUSerius](https://github.com/googlefonts/are-you-serious/issues/2#issuecomment-870693956) as reference
- [x] The German Double SS need to be fixed. This [article](https://www.lucasfonts.com/learn/1E9E) is a good reference
- [x] Currency symbols are related to the overall design and have balanced proportions
- [x] `ordfeminine` and `ordmasculine` as well as superior numbers are well proportioned and with a balanced stem thickness. [Issue of reference](https://github.com/googlefonts/cherish/issues/2#issuecomment-872268750)

**Comment by RobLeuschke** [comment]
MoonDance is complete. Some glyphs still have overlaps.

**Comment by vv-monsalve** [comment]
Hi @RobLeuschke, Moon Dance has some spacing & kerning issues: 

- [x] Some common kerning pairs are missing
- [x] There is a positive kerning between `space` and many uppercase letters. Please review if either the space is too short or the left sidebearing of the letters needs a higher value. 
- [x] As the uppercase set for MoonDance is more Roman style, they could be used in "All caps". Therefore the spacing among them should be improved.

**Weight Issues.**
- [x] Also, the `l` and `o` letters seem to be too light and darker respectively. In the o it could be the loop to form the eye.

Please take the latest file at the root of the 'sources' folder in DropBox to inspect the entire font and solve all the cases. Remember you could use the [sidebearing arithmetics in glyphs](https://glyphsapp.com/learn/spacing) to make it easier and consistent whenever possible.

<img width="229" alt="Screen Shot 2021-10-11 at 10 20 23" src="https://user-images.githubusercontent.com/48698976/136818778-d1b9e38d-8554-44e7-ae8c-ed7fc51db1b4.png">
<img width="391" alt="Screen Shot 2021-10-11 at 10 20 28" src="https://user-images.githubusercontent.com/48698976/136818790-28175f7d-7d2a-4d04-bdfe-0bda7a5eb3c3.png">
<img width="746" alt="Screen Shot 2021-10-11 at 10 22 12" src="https://user-images.githubusercontent.com/48698976/136819364-60268699-08f1-4cb7-81b4-3a7461417e6f.png">
<img width="662" alt="Screen Shot 2021-10-11 at 10 22 30" src="https://user-images.githubusercontent.com/48698976/136819374-fe62efe4-3eb4-4c42-b238-419817f36c7d.png">
<img width="618" alt="Screen Shot 2021-10-11 at 10 41 07" src="https://user-images.githubusercontent.com/48698976/136819394-f8b8f2a9-b305-4e95-a139-8292f68ca19c.png">
<img width="1368" alt="Screen Shot 2021-10-11 at 10 35 35" src="https://user-images.githubusercontent.com/48698976/136819385-28f7c77b-afd5-486e-a647-e16d1269234e.png">




<img width="171" alt="Screen Shot 2021-10-11 at 10 21 16" src="https://user-images.githubusercontent.com/48698976/136819551-87e3485c-1867-4c1f-9c1a-9030cee2bf5f.png">
<img width="282" alt="Screen Shot 2021-10-11 at 10 21 36" src="https://user-images.githubusercontent.com/48698976/136819554-dee9df35-a131-45e0-9b91-25562460ecaf.png">

**Comment by RobLeuschke** [comment]
I will need to have a meeting about the kerning issues.

**Comment by vv-monsalve** [comment]
Please let me know your questions

**Comment by RobLeuschke** [comment]
I have corrected the kerning pairs and made adjustments to some of the letter weights.

**Comment by vv-monsalve** [comment]
Thanks. I'll download the file from DB and let you know if anything else is needed.

**Comment by vv-monsalve** [comment]
Hi @RobLeuschke, the latest source file still have some issues with the spacing and kerning, like unnecessary kerning pairs for things that would be covered systematically by adjusting the spacing before. 
E.g. the space between `AH` should be the same or similar to `AF` and `AK` but the latter are tighter.
This is happening due to the `AH` is being solved through a kerning pair (+40) instead of adjusting the right sidebearing of the A.

You would like to follow the [Glyphs tutorial](https://glyphsapp.com/learn/spacing) to better grasp how this could be solved, especially making use of the sidebearing arithmetic option.

<img width="1086" alt="Screen Shot 2021-10-19 at 18 09 27" src="https://user-images.githubusercontent.com/48698976/138003046-62abcee0-03b2-42fe-b8e9-1cc57e3552b3.png">

**Comment by RobLeuschke** [comment]
okie dokie

(are you familiar with that American phrase?)

R0b

**Comment by vv-monsalve** [comment]
> (are you familiar with that American phrase?)

Yes, we used to use it a lot here in Colombia. I don't know if it has a particular story though, is there one?.

**Comment by vv-monsalve** [comment]
Hi @RobLeuschke after pulling the latest source file in DropBox (date 24/10/21) the spacing is starting to look better.

- However, it seems the right sidebearings are looser than the left ones, which is leading to some gaps or inconsistencies (e.g. `T`, `J` and `V`)
<img width="911" alt="Screen Shot 2021-10-25 at 16 31 55" src="https://user-images.githubusercontent.com/48698976/138775208-f4cfcc38-c3ff-4cc2-97b6-10558c95eab8.png">
<img width="860" alt="Screen Shot 2021-10-25 at 16 33 16" src="https://user-images.githubusercontent.com/48698976/138775217-3eb15613-8c5a-490e-a85a-c87acb1bfae4.png">
<img width="800" alt="Screen Shot 2021-10-25 at 16 33 53" src="https://user-images.githubusercontent.com/48698976/138775541-2fa2b8b7-3003-4474-bf46-2f68deb6f24c.png">
<br>
- In other cases it is backwards, it is the left one the one that is loose (e.g. `M`)
<img width="954" alt="Screen Shot 2021-10-25 at 16 34 23" src="https://user-images.githubusercontent.com/48698976/138775580-f45d9023-d591-4a32-8404-13fb8cc867d7.png">
<br>
- And, given the `A` is a triangular shape, therefore with a bigger withe area around, it can't have the same value as `H`, it is leading to some crashes and gaps with different letters. Please keep in mind that for all the cases the combination with HH and OO as key characters is crucial. The sequence with HH must be solved first and without kerning. Typically, no kerning is expected between any letter and H. Then it goes the sequence with OO which in some particular cases (like AO) could need a small amount of kerning. 
<img width="812" alt="Screen Shot 2021-10-25 at 16 32 31" src="https://user-images.githubusercontent.com/48698976/138775884-c6fd4908-5489-46cc-b60c-6c91aab3aa70.png">
